# Generated by Django 4.2.1 on 2023-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=15000)),
                ('name', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
