# Generated by Django 4.2.1 on 2023-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=15000)),
                ('name', models.CharField(max_length=100)),
                ('answer', models.TextField(max_length=15000)),
            ],
        ),
    ]
